version: '3.8'

services:
  # 后端API服务
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    volumes:
      - ./src/backend:/app:delegated
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=gateway/app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SECRET_KEY=dev_secret_key
      - JWT_SECRET_KEY=jwt_dev_secret_key
      - JWT_ACCESS_TOKEN_EXPIRES=3600
      - JWT_REFRESH_TOKEN_EXPIRES=604800
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ecohub
      - MONGO_URI=mongodb://mongo:27017/ecohub
      - REDIS_URL=redis://redis:6379/0
    command: flask run --host=0.0.0.0 --port=5000
    depends_on:
      - db
      - mongo
      - redis
    networks:
      - ecohub-network
    user: "1000:1000"  # 使用与主机相同的用户ID
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # 前端服务
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    volumes:
      - ./src/frontend:/app:delegated
      - /app/node_modules
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - ecohub-network
    user: "1000:1000"  # 使用与主机相同的用户ID
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  # PostgreSQL 数据库
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=ecohub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ecohub-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # MongoDB 数据库
  mongo:
    image: mongo:5
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - ecohub-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Redis 缓存
  redis:
    image: redis:6
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - ecohub-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # pgAdmin - PostgreSQL管理工具
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@ecohub.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - ecohub-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Mongo Express - MongoDB管理工具
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - ecohub-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Redis Commander - Redis管理工具
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"
    depends_on:
      - redis
    networks:
      - ecohub-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  postgres_data:
  mongo_data:
  redis_data:

networks:
  ecohub-network:
    driver: bridge
